import type { SiteContent, ContentEntry, PageSection } from '@/models/content';
import { Photo } from './photo';
export function Shell({site,children}:{site:SiteContent;children:React.ReactNode}) {
  return <><a className="skip" href="#contenido">Saltar al contenido</a>{site.settings.demo&&<div className="demo-bar">Vista de demostración · Fotografías y propuestas de muestra</div>}<header className="header"><a className="brand" href="/"><span className="brand-mark" aria-hidden="true">✳</span><span>{site.settings.name}<small>{site.settings.tagline}</small></span></a><nav className="desktop-nav" aria-label="Navegación principal">{site.settings.navigation.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</nav><a className="button small" href="/cotizar">Cotizar mi evento <span aria-hidden="true">↗</span></a><details className="mobile-menu"><summary aria-label="Abrir navegación">☰</summary><nav aria-label="Navegación móvil">{site.settings.navigation.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</nav></details></header><main id="contenido">{children}</main><footer><div className="footer-grid"><div><div className="brand">{site.settings.name}</div><p>{site.settings.footer}</p></div><nav aria-label="Pie de página">{site.settings.navigation.map(n=><a key={n.href} href={n.href}>{n.label}</a>)}</nav><div><p>Conversemos sobre tu evento</p>{site.settings.email&&<a href={`mailto:${site.settings.email}`}>{site.settings.email}</a>}<a href="/cotizar">Solicitar una propuesta ↗</a></div></div><div className="footer-bottom"><span>{site.settings.tagline}</span><a href="/admin">Administración</a></div></footer></>;
}
export function EntryCards({site,entries}:{site:SiteContent;entries:ContentEntry[]}) {
  return <div className="cards">{entries.map((e,i)=><article className="entry-card" key={e.id}><a href={`/${e.kind}/${e.slug}`} className="image-link" aria-label={e.title}><Photo asset={site.media.find(m=>m.id===e.imageId)}/></a><div className="card-top"><span className="eyebrow">{String(i+1).padStart(2,'0')}</span><a aria-label={`Ver ${e.title}`} href={`/${e.kind}/${e.slug}`}>↗</a></div><h3><a href={`/${e.kind}/${e.slug}`}>{e.title}</a></h3><p>{e.description}</p></article>)}</div>;
}
const entriesFor=(site:SiteContent,type:string)=>site.entries.filter(e=>e.kind===type&&e.status==='published'&&e.featured).sort((a,b)=>a.sortOrder-b.sortOrder);
function Hero({site,section:s}:{site:SiteContent;section:PageSection}) {return <section className="hero"><div className="hero-copy"><p className="eyebrow">{site.settings.tagline} <span>— Lima, Perú</span></p><h1>{s.title}</h1><p className="lead">{s.description}</p><div className="actions"><a className="button" href="/cotizar">Cotizar mi evento ↗</a><a className="text-link" href="/menus">Explorar menús →</a></div><div className="hero-note"><span aria-hidden="true">✳</span> {site.settings.footer}</div></div><div className="hero-picture"><Photo asset={site.media.find(m=>m.id===s.imageId)} priority/><div className="picture-label">{site.settings.tagline}</div></div></section>}
function Catalog({site,section:s}:{site:SiteContent;section:PageSection}) {const entries=entriesFor(site,s.type);if(!entries.length)return null;return <section className="section wrap"><div className="section-heading"><div><p className="eyebrow">{s.type==='menus'?'A tu gusto':'Nuestras especialidades'}</p><h2>{s.title}</h2><p>{s.description}</p></div><a className="text-link" href={`/${s.type}`}>Ver todos →</a></div><EntryCards site={site} entries={entries}/></section>}
function TextImage({site,section:s}:{site:SiteContent;section:PageSection}) {return <section className="story"><Photo asset={site.media.find(m=>m.id===s.imageId)}/><div><p className="eyebrow">{site.settings.tagline}</p><h2>{s.title}</h2><p>{s.description}</p><a className="text-link" href="/cotizar">Hablemos de tu evento ↗</a></div></section>}
function Faq({site,section:s}:{site:SiteContent;section:PageSection}) {if(!site.faqs.length)return null;return <section className="section wrap faq"><div><p className="eyebrow">Preguntas frecuentes</p><h2>{s.title}</h2><p>{s.description}</p></div><div>{site.faqs.map(f=><details key={f.id}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div></section>}
function Cta({section:s}:{site:SiteContent;section:PageSection}) {return <section className="cta"><span aria-hidden="true">✳</span><h2>{s.title}</h2><p>{s.description}</p><a className="button light" href="/cotizar">Organicemos tu evento ↗</a></section>}
const registry = {hero:Hero,servicios:Catalog,menus:Catalog,texto:TextImage,faq:Faq,cta:Cta};
export function Sections({site}:{site:SiteContent}) {return <>{site.sections.filter(s=>s.visible).sort((a,b)=>a.sortOrder-b.sortOrder).map(section=>{const Block=registry[section.type];return <Block key={section.id} site={site} section={section}/>;})}</>}
