'use client';
import { useState } from 'react';
import type { SiteContent } from '@/models/content';
export function Quote({site,selection}:{site:SiteContent;selection:string}){
  const [step,setStep]=useState(1);const [data,setData]=useState({event:'',date:'',district:'',people:'',selection,name:'',phone:'',notes:''});const [ready,setReady]=useState(false);
  const chosen=site.entries.find(e=>e.id===data.selection);const summary=`${site.settings.whatsappMessage}\n\nEvento: ${data.event}\nFecha: ${data.date}\nDistrito: ${data.district}\nPersonas: ${data.people}\nPropuesta: ${chosen?.title||'Necesito orientación'}\nNombre: ${data.name}\nTeléfono: ${data.phone}\nComentarios: ${data.notes}`;
  const field=(key:keyof typeof data,label:string,type='text',required=true)=><label className="field">{label}<input required={required} type={type} value={data[key]} min={type==='number'?1:type==='date'?new Date().toLocaleDateString('en-CA'):undefined} max={type==='number'?100000:undefined} maxLength={200} onChange={e=>{setData({...data,[key]:e.target.value});setReady(false);}}/></label>;
  return <div className="quote-layout"><div><div className="stepper">{['Tu evento','La propuesta','Contacto'].map((label,i)=><span key={label} aria-current={step===i+1?'step':undefined}>{i+1}. {label}</span>)}</div><form onSubmit={e=>{e.preventDefault();if(step<3)setStep(step+1);else setReady(true);}}><div className="form-grid">{step===1&&<>{field('event','Tipo de evento')}{field('date','Fecha del evento','date')}{field('district','Distrito')}{field('people','Número de personas','number')}</>}{step===2&&<><label className="field wide">Servicio o menú<select value={data.selection} onChange={e=>{setData({...data,selection:e.target.value});setReady(false);}}><option value="">Necesito orientación</option>{site.entries.filter(e=>e.status==='published'&&['servicios','menus','complementos'].includes(e.kind)).map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label><label className="field wide">Comentarios y complementos que te interesan<textarea value={data.notes} maxLength={2000} onChange={e=>{setData({...data,notes:e.target.value});setReady(false);}}/></label></>}{step===3&&<>{field('name','Nombre')}{field('phone','Teléfono','tel')}<p className="wide">Prepararemos un resumen para abrirlo en WhatsApp. Esta web todavía no guarda solicitudes de cotización.</p></>}</div><div className="form-actions">{step>1&&<button type="button" className="ghost" onClick={()=>{setStep(step-1);setReady(false);}}>← Atrás</button>}<button className="button" type="submit">{step<3?'Continuar →':'Revisar resumen'}</button></div></form>{ready&&<div className="panel"><h2>Revisa antes de continuar</h2><p className="prose">{summary}</p>{site.settings.whatsapp?<a className="button" target="_blank" rel="noreferrer" href={`https://wa.me/${site.settings.whatsapp}?text=${encodeURIComponent(summary)}`}>Continuar por WhatsApp ↗</a>:<p className="notice">El número de WhatsApp aún no está configurado. Este recorrido es de demostración.</p>}<p>Abrir WhatsApp no envía el mensaje. Podrás revisarlo y enviarlo desde esa aplicación.</p></div>}</div><aside className="quote-summary"><p className="eyebrow">Tu reunión, a tu medida</p><h2>Una buena mesa empieza por conocerte.</h2><p>{data.event||'Cuéntanos qué celebras'}</p><p>{data.people?`${data.people} personas`:'Número de invitados por definir'}</p><p>{data.district||'Distrito por definir'}</p><p>{chosen?.title||'Te ayudamos a elegir una propuesta'}</p></aside></div>;
}
