import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const base = process.env.TEST_ORIGIN || 'http://localhost:3000';
const password = readFileSync('.dev.vars','utf8').match(/ADMIN_PASSWORD="([^"]+)"/)[1];
const login = await fetch(`${base}/api/session`, {method:'POST',headers:{origin:base,'Content-Type':'application/json'},body:JSON.stringify({password})});
assert.equal(login.status,204,'admin login');
const cookie=login.headers.get('set-cookie').split(';')[0];
const headers={origin:base,cookie,'Content-Type':'application/json'};
const read=()=>fetch(`${base}/api/content`,{headers}).then(r=>r.json());
const original=await read();
const save=body=>fetch(`${base}/api/content`,{method:'PUT',headers,body:JSON.stringify(body)});
let state=structuredClone(original);
try {
  assert.equal((await fetch(`${base}/api/content`)).status,403,'anonymous read blocked');
  assert.equal((await fetch(`${base}/api/content`,{method:'PUT',headers:{origin:base},body:'{}'})).status,403,'anonymous write blocked');
  assert.equal((await fetch(`${base}/api/content`,{method:'PUT',headers:{...headers,origin:'https://example.org'},body:'{}'})).status,403,'cross-origin write blocked');
  state.entries.push({...state.entries.find(e=>e.kind==='menus'),id:'smoke-menu',slug:'smoke-menu',title:'Menú de verificación',status:'draft',seo:{title:'SEO de verificación',description:'Descripción verificada del menú.',noindex:false}});
  let r=await save(state);assert.equal(r.status,200,await r.clone().text());state=await r.json();
  assert.equal((await fetch(`${base}/menus/smoke-menu`)).status,404,'draft is not public');
  state.entries.find(e=>e.id==='smoke-menu').status='published';
  state.settings.tagline='Frase verificada desde CMS';
  r=await save(state);assert.equal(r.status,200);const stale=structuredClone(state);state=await r.json();
  const detail=await fetch(`${base}/menus/smoke-menu`);assert.equal(detail.status,200);const html=await detail.text();
  assert.ok(html.includes('<title>SEO de verificación</title>'),'SEO rendered on server');
  assert.ok(html.includes('Descripción verificada del menú.'),'description rendered');
  assert.equal((html.match(/<h1[\s>]/g)||[]).length,1,'one H1');
  assert.ok(html.includes('Frase verificada desde CMS'),'shared settings reflected');
  assert.equal((await save(stale)).status,409,'stale updates rejected');
  const invalid=structuredClone(state);invalid.entries.at(-1).slug='../bad';assert.equal((await save(invalid)).status,400,'invalid slug rejected');
  const indexable=structuredClone(state);indexable.settings.indexable=true;assert.equal((await save(indexable)).status,400,'demo indexation rejected');
  const form=new FormData();form.set('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1sAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'test.png');
  const upload=await fetch(`${base}/api/media`,{method:'POST',headers:{origin:base,cookie},body:form});assert.equal(upload.status,200);const asset=await upload.json();
  const image=await fetch(base+asset.url);assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');
  state.media.push(asset);state.entries.at(-1).imageId=asset.id;r=await save(state);assert.equal(r.status,200);state=await r.json();
  assert.ok((await fetch(`${base}/menus/smoke-menu`).then(r=>r.text())).includes(asset.url),'uploaded image selected by menu');
  assert.ok((await fetch(`${base}/robots.txt`).then(r=>r.text())).includes('Disallow: /'),'demo crawling disabled');
  assert.ok(!(await fetch(`${base}/sitemap.xml`).then(r=>r.text())).includes('<loc>'),'demo sitemap empty');
  console.log('PASS: access, CSRF, drafts, publishing, SSR SEO, single H1, settings, concurrency, validation, upload and media references.');
} finally {
  const latest=await read();const restore=await save({...original,version:latest.version});assert.equal(restore.status,200,'restore original content');
}
